#!/bin/zsh
set -e
TOOL_NAME=./x
PROJECT_NAME=physical-values-rust
. ../ideal-build-tool/buildtool

tool cargo

build with cargo build

run formatter with cargo fmt 
run linter with cargo clippy 
run check with cargo check

start with ./target/debug/physical-values-rust

cleanup target

woot