#!/bin/zsh
set -e
TOOL_NAME=./x
PROJECT_NAME=process-runner-kt
. ../ideal-build-tool/buildtool

build with ./gradlew :assemble
start with ./gradlew :runDebugExecutableNative 

run gradle task list with ./gradlew :tasks 
run tests with ./gradlew :check
cleanup build .gradle

woot