#!/bin/zsh
set -euo pipefail

if [[ -z "$AWS_ACCESS_KEY_ID" ]] || [[ -z "$AWS_SECRET_ACCESS_KEY" ]]; then
  echo "Please define AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to deploy manually"
  exit 1
fi

./gradlew :telegrambot:dockerPush


